"""校准芯片生成器：产出用于标定机器/耗材参数的标准 G-code 试件。

设计（解耦原理）：
6 段薄壁方塔，自下而上编码 {风扇 0/50/100%} × {慢速/快速} 两组变量：
  段1 慢速 风扇0    段2 快速 风扇0
  段3 慢速 风扇50   段4 快速 风扇50
  段5 慢速 风扇100  段6 快速 风扇100
- 同速不同扇的段对比 → 差异全部归因风扇散热强度（h_fan_scale）
- 同扇不同速的段对比 → 钉死层时敏感性与结合阈值（cold_below/T_bond）
用户打印后逐段掰断并报告「易断/结实」，拟合器据此反推参数。
"""
from __future__ import annotations

import math

from ..thermal.materials import get_material

_FIL_AREA = math.pi / 4 * 1.75 ** 2   # 1.75 丝截面积
_BEAD_W = 0.42
_BEAD_H = 0.2


def generate_chip(material: str = "PLA", *, section_layers: int = 30,
                  size: float = 30.0, slow_feed: float = 15.0,
                  fast_feed: float = 150.0) -> tuple[str, dict]:
    """生成校准芯片 G-code。返回 (gcode_text, manifest)。

    manifest 含 6 段的层范围/风扇/速度，以及几何与耗时预估，
    供前端表单与拟合器（按层号分段采样界面温度）共用。
    """
    m = get_material(material)
    nozzle = m.nozzle
    bed = m.bed

    sections = [
        {"section": 1, "fan": 0.0, "feed": slow_feed},
        {"section": 2, "fan": 0.0, "feed": fast_feed},
        {"section": 3, "fan": 0.5, "feed": slow_feed},
        {"section": 4, "fan": 0.5, "feed": fast_feed},
        {"section": 5, "fan": 1.0, "feed": slow_feed},
        {"section": 6, "fan": 1.0, "feed": fast_feed},
    ]
    for s in sections:
        s["layers"] = section_layers
        s["z_from"] = round(0.2 + (s["section"] - 1) * section_layers * _BEAD_H, 3)
        s["z_to"] = round(0.2 + s["section"] * section_layers * _BEAD_H, 3)

    cx = cy = 100.0
    half = size / 2.0
    wall_offset = _BEAD_W  # 第二道墙内偏
    lines: list[str] = [
        "; generated by thermal-assess calibration chip",
        f"; material = {m.name}",
        f"; nozzle_temperature = {nozzle}",
        f"; hot_plate_temp = {bed}",
        "; layer_height = 0.2",
        f"; sections = {len(sections)}",
        "M82",
        f"M104 S{nozzle}",
        f"M140 S{bed}",
        "G28",
        "G92 E0",
        "G1 Z0.2 F600",
    ]

    e = 0.0
    x = y = 0.0
    total_layers = len(sections) * section_layers

    def travel(nx: float, ny: float, f: float) -> None:
        nonlocal x, y
        lines.append(f"G1 X{nx:.3f} Y{ny:.3f} F{f * 60:.0f}")
        x, y = nx, ny

    def extrude_to(nx: float, ny: float, f: float) -> None:
        nonlocal x, y, e
        seg = math.hypot(nx - x, ny - y)
        e += seg * (_BEAD_W * _BEAD_H) / _FIL_AREA
        lines.append(f"G1 X{nx:.3f} Y{ny:.3f} E{e:.5f} F{f * 60:.0f}")
        x, y = nx, ny

    for s in sections:
        fan_byte = round(s["fan"] * 255)
        z_top = round(0.2 + s["section"] * section_layers * _BEAD_H, 3)
        lines.append(f";SECTION {s['section']} fan={s['fan']} feed={s['feed']} z={s['z_from']}-{s['z_to']}")
        lines.append(f"M106 S{fan_byte}")
        start_z = round(0.2 + (s["section"] - 1) * section_layers * _BEAD_H, 3)
        for li in range(section_layers):
            z = round(start_z + (li + 1) * _BEAD_H, 3)
            lines.append(f"G1 Z{z:.3f} F600")
            # 两道方环墙：外道 size，内道 size-2*wall_offset
            for half_w in (half, half - wall_offset):
                pts = [(cx - half_w, cy - half_w), (cx + half_w, cy - half_w),
                       (cx + half_w, cy + half_w), (cx - half_w, cy + half_w),
                       (cx - half_w, cy - half_w)]
                travel(pts[0][0], pts[0][1], s["feed"])
                for px, py in pts[1:]:
                    extrude_to(px, py, s["feed"])

    lines += ["M107", "M104 S0"]
    manifest = {
        "material": m.name,
        "nozzle_temp": nozzle,
        "bed_temp": bed,
        "layer_height": _BEAD_H,
        "total_layers": total_layers,
        "size_mm": size,
        "sections": sections,
        "est_layers_per_section": section_layers,
    }
    return "\n".join(lines), manifest


def section_of_layer(layer_idx: int, section_layers: int = 30) -> int:
    """0 基层号 → 0 基段号。"""
    return layer_idx // section_layers
