"""标准量化测试件：温度塔与 VFA 速度塔。

与掰断芯片互补的量化标定路线——观测是数值型边界而非主观二值：

- 温度塔：同几何、逐块 M104 变喷嘴温度。用户报告每块质量（弱/可用/过热），
  拟合出结合窗口两端：T_bond（弱/可用边界）与 T_sag（可用/过热边界）。
- VFA 速度塔：单壁圆/方管，逐带加速。用户报告出现瑕疵（孔洞/拉丝）的
  起始档位 → 钉死流量→质量悬崖（flow_ref/span）。

两件各打一次即可把 TQI 窗口与流量参数标定到绝对温度/速度上。
"""
from __future__ import annotations

import math

from ..thermal.materials import get_material

_FIL_AREA = math.pi / 4 * 1.75 ** 2


def _emit_square_wall(lines, e_state, cx, cy, half, feed, wall=0.42):
    x, y = e_state["x"], e_state["y"]
    pts = [(cx - half, cy - half), (cx + half, cy - half),
           (cx + half, cy + half), (cx - half, cy + half), (cx - half, cy - half)]
    dx, dy = pts[0][0] - x, pts[0][1] - y
    e_state["e"] += math.hypot(dx, dy) * wall * e_state["h"] / _FIL_AREA
    lines.append(f"G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} E{e_state['e']:.5f} F{feed * 60:.0f}")
    e_state["x"], e_state["y"] = pts[0]
    for px, py in pts[1:]:
        dx, dy = px - e_state["x"], py - e_state["y"]
        e_state["e"] += math.hypot(dx, dy) * wall * e_state["h"] / _FIL_AREA
        lines.append(f"G1 X{px:.3f} Y{py:.3f} E{e_state['e']:.5f} F{feed * 60:.0f}")
        e_state["x"], e_state["y"] = px, py


def generate_temp_tower(material: str = "PLA", *, temps: list[float] | None = None,
                        block_layers: int = 40, size: float = 25.0,
                        layer_h: float = 0.2) -> tuple[str, dict]:
    """温度塔：7 块逐块变喷嘴温度（默认材料推荐值 +10 → −20，步进 5）。

    每块起始 G4 S8 驻留让喷嘴温度稳定；块内 3 道墙 + 稀疏填充。
    """
    m = get_material(material)
    if temps is None:
        temps = [m.nozzle + 10 - 5 * i for i in range(7)]

    lines = [
        "; generated by thermal-assess temperature tower",
        f"; material = {m.name}",
        f"; nozzle_temperature = {m.nozzle}",
        f"; hot_plate_temp = {m.bed}",
        "; layer_height = 0.2",
        f"; blocks = {len(temps)}",
        "M82",
        f"M104 S{temps[0]}", "M109 S{0}".format(temps[0]),
        f"M140 S{m.bed}", "G28", "G92 E0", "G1 Z0.2 F600",
    ]

    e = 0.0
    x = y = 0.0
    h = layer_h
    cx = cy = 100.0
    half = size / 2.0
    blocks = []
    layer_no = 0

    for bi, temp in enumerate(temps, 1):
        z0 = round(0.2 + (bi - 1) * block_layers * h, 3)
        z1 = round(0.2 + bi * block_layers * h, 3)
        lines.append(f";BLOCK {bi} temp={temp} z={z0}-{z1}")
        lines.append(f"M104 S{temp}")
        lines.append("G4 S8")  # 驻留：让熔池温度进入新设定
        for li in range(block_layers):
            z = round(0.2 + (layer_no + 1) * h, 3)
            lines.append(f"G1 Z{z:.3f} F600")
            # 3 道墙
            for w in range(3):
                hw = half - w * 0.42
                pts = [(cx - hw, cy - hw), (cx + hw, cy - hw), (cx + hw, cy + hw),
                       (cx - hw, cy + hw), (cx - hw, cy - hw)]
                dx, dy = pts[0][0] - x, pts[0][1] - y
                e += math.hypot(dx, dy) * 0.42 * h / _FIL_AREA
                lines.append(f"G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} E{e:.5f} F{min(150.0, temp * 0.7) * 60:.0f}")
                x, y = pts[0]
                for px, py in pts[1:]:
                    dx, dy = px - x, py - y
                    e += math.hypot(dx, dy) * 0.42 * h / _FIL_AREA
                    lines.append(f"G1 X{px:.3f} Y{py:.3f} E{e:.5f} F{min(150.0, temp * 0.7) * 60:.0f}")
                    x, y = px, py
            # 稀疏填充（8mm 间距横线）
            yy = cy - half + 1.0
            d = 1
            while yy < cy + half - 1.0:
                x0, x1 = (cx - half + 1.0, cx + half - 1.0) if d > 0 else (cx + half - 1.0, cx - half + 1.0)
                dx, dy = x0 - x, yy - y
                e += math.hypot(dx, dy) * 0.42 * h / _FIL_AREA
                lines.append(f"G1 X{x0:.3f} Y{yy:.3f} E{e:.5f} F{min(200.0, temp) * 60:.0f}")
                x, y = x0, yy
                dx, dy = x1 - x, 0.0
                e += math.hypot(dx, dy) * 0.42 * h / _FIL_AREA
                lines.append(f"G1 X{x1:.3f} Y{yy:.3f} E{e:.5f} F{min(200.0, temp) * 60:.0f}")
                x, y = x1, yy
                d = -d
                yy += 8.0
            layer_no += 1

        blocks.append({"block": bi, "temp": temp, "z_from": z0, "z_to": z1,
                       "layers": block_layers})

    lines += ["M104 S0", "M107"]
    manifest = {
        "kind": "temp_tower", "material": m.name, "nozzle_default": m.nozzle,
        "bed_temp": m.bed, "layer_height": h, "total_layers": layer_no,
        "blocks": blocks,
    }
    return "\n".join(lines), manifest


def generate_vfa(material: str = "PLA", *, speeds: list[float] | None = None,
                 band_layers: int = 50, size: float = 25.0,
                 layer_h: float = 0.2, fan: float = 1.0) -> tuple[str, dict]:
    """VFA 速度塔：单壁方管，逐带加速（默认 20→300mm/s）。

    观测：从哪一档开始出现孔洞/拉丝（流量→质量悬崖）。
    """
    m = get_material(material)
    if speeds is None:
        speeds = [20, 30, 40, 60, 80, 100, 120, 150, 180, 210, 240, 270, 300]

    lines = [
        "; generated by thermal-assess VFA tower",
        f"; material = {m.name}",
        f"; nozzle_temperature = {m.nozzle}",
        f"; hot_plate_temp = {m.bed}",
        "; layer_height = 0.2",
        f"; bands = {len(speeds)}",
        "M82",
        f"M104 S{m.nozzle}", f"M140 S{m.bed}", "G28", "G92 E0",
        f"M106 S{round(fan * 255)}",
        "G1 Z0.2 F600",
    ]

    e = 0.0
    x = y = 0.0
    h = layer_h
    cx = cy = 100.0
    half = size / 2.0
    bands = []
    layer_no = 0

    for bi, speed in enumerate(speeds, 1):
        z0 = round(0.2 + (bi - 1) * band_layers * layer_h, 3)
        z1 = round(0.2 + bi * band_layers * layer_h, 3)
        lines.append(f";BAND {bi} speed={speed} z={z0}-{z1}")
        for li in range(band_layers):
            z = round(0.2 + (layer_no + 1) * layer_h, 3)
            lines.append(f"G1 Z{z:.3f} F600")
            pts = [(cx - half, cy - half), (cx + half, cy - half),
                   (cx + half, cy + half), (cx - half, cy + half), (cx - half, cy - half)]
            dx, dy = pts[0][0] - x, pts[0][1] - y
            e += math.hypot(dx, dy) * 0.42 * h / _FIL_AREA
            lines.append(f"G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} E{e:.5f} F{speed * 60:.0f}")
            x, y = pts[0]
            for px, py in pts[1:]:
                dx, dy = px - x, py - y
                e += math.hypot(dx, dy) * 0.42 * h / _FIL_AREA
                lines.append(f"G1 X{px:.3f} Y{py:.3f} E{e:.5f} F{speed * 60:.0f}")
                x, y = px, py
            layer_no += 1

        bands.append({"band": bi, "speed": speed, "z_from": z0, "z_to": z1,
                      "layers": band_layers,
                      "flow_mm3s": round(0.42 * layer_h * speed, 2)})

    lines += ["M107", "M104 S0"]
    manifest = {
        "kind": "vfa", "material": m.name, "nozzle_temp": m.nozzle, "bed_temp": m.bed,
        "layer_height": h, "total_layers": layer_no, "fan": fan,
        "bands": bands,
    }
    return "\n".join(lines), manifest
