"""合成 G-code 生成器：产生确定性的 Orca/Bambu 风格 G-code 用于测试。

场景覆盖：
- 逐层堆叠的方板（外墙 + 稀疏填充），层内速度可调 → 控制层时间
- 两段式速度件：前半慢速 / 后半快速 → 验证界面温度随层时间的单调性
"""
from __future__ import annotations

import math

_FIL_AREA = math.pi / 4 * 1.75 ** 2  # 1.75 丝截面积 mm²
_BEAD = 0.42 * 0.2                    # 单珠截面积 mm²


def _e_for(length_mm: float) -> float:
    return length_mm * _BEAD / _FIL_AREA


def _header(material: str, nozzle: float, bed: float) -> str:
    return "\n".join([
        "; generated by thermal-assess test generator",
        "; slicer = testgen",
        f"; filament_type = {material}",
        "; filament_diameter = 1.75",
        f"; nozzle_temperature = {nozzle}",
        f"; hot_plate_temp = {bed}",
        "; layer_height = 0.2",
        "",
        "M82",
        f"M104 S{nozzle}",
        f"M140 S{bed}",
        "G28",
        "G92 E0",
        "G1 Z0.2 F600",
    ])


class _Gen:
    """带位置/E 状态的最小 G-code 写出器。"""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.x = self.y = self.z = 0.0
        self.e = 0.0

    def travel(self, x: float, y: float, f: float) -> None:
        self.lines.append(f"G1 X{x:.3f} Y{y:.3f} F{f * 60:.0f}")
        self.x, self.y = x, y

    def extrude_to(self, x: float, y: float, f: float) -> None:
        seg = math.hypot(x - self.x, y - self.y)
        self.e += _e_for(seg)
        self.lines.append(f"G1 X{x:.3f} Y{y:.3f} E{self.e:.5f} F{f * 60:.0f}")
        self.x, self.y = x, y

    def z_up(self, z: float) -> None:
        self.lines.append(f";LAYER_CHANGE")
        self.lines.append(f";Z:{z:.3f}")
        self.lines.append(f"G1 Z{z:.3f} F600")
        self.z = z

    def rect_layer(self, cx: float, cy: float, half: float, feed: float) -> None:
        pts = [(cx - half, cy - half), (cx + half, cy - half),
               (cx + half, cy + half), (cx - half, cy + half), (cx - half, cy - half)]
        self.lines.append(";TYPE:Outer wall")
        self.travel(*pts[0], f=feed)
        for p in pts[1:]:
            self.extrude_to(p[0], p[1], f=feed)


def generate_box_gcode(layers: int = 30, size: float = 40.0,
                       feed: float = 50.0, material: str = "PLA") -> str:
    """标准测试件：size(mm) 见方、layers 层、恒定打印速度。"""
    g = _Gen()
    g.lines.append(_header(material, 210 if material == "PLA" else 240,
                           55 if material == "PLA" else 75))
    cx = cy = 100.0
    for li in range(layers):
        g.z_up(round(0.2 + li * 0.2, 3))
        g.rect_layer(cx, cy, size / 2, feed)
    g.lines += ["M107", "M104 S0"]
    return "\n".join(g.lines)


def generate_two_rate_gcode(material: str = "PLA") -> str:
    """两段式测试件：前 10 层 10mm/s（长层时，界面冷），后 10 层 150mm/s
    （短层时，界面热）。"""
    g = _Gen()
    g.lines.append(_header(material, 210, 55))
    cx = cy = 100.0
    for li in range(20):
        g.z_up(round(0.2 + li * 0.2, 3))
        feed = 10.0 if li < 10 else 150.0
        g.rect_layer(cx, cy, 20.0, feed)
    g.lines += ["M107", "M104 S0"]
    return "\n".join(g.lines)
